// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateCatRes interface {
	createCatRes()
}

type CreateToiletRes interface {
	createToiletRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteCatRes interface {
	deleteCatRes()
}

type DeleteToiletRes interface {
	deleteToiletRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListCatRes interface {
	listCatRes()
}

type ListCatToiletsRes interface {
	listCatToiletsRes()
}

type ListToiletRes interface {
	listToiletRes()
}

type ListUserCatsRes interface {
	listUserCatsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadCatOwnerRes interface {
	readCatOwnerRes()
}

type ReadCatRes interface {
	readCatRes()
}

type ReadToiletCatRes interface {
	readToiletCatRes()
}

type ReadToiletRes interface {
	readToiletRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateCatRes interface {
	updateCatRes()
}

type UpdateToiletRes interface {
	updateToiletRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
