// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCat implements createCat operation.
//
// Creates a new Cat and persists it to storage.
//
// POST /cats
func (UnimplementedHandler) CreateCat(ctx context.Context, req *CreateCatReq) (r CreateCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateToilet implements createToilet operation.
//
// Creates a new Toilet and persists it to storage.
//
// POST /toilets
func (UnimplementedHandler) CreateToilet(ctx context.Context, req *CreateToiletReq) (r CreateToiletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Creates a new User and persists it to storage.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserReq) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCat implements deleteCat operation.
//
// Deletes the Cat with the requested ID.
//
// DELETE /cats/{id}
func (UnimplementedHandler) DeleteCat(ctx context.Context, params DeleteCatParams) (r DeleteCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteToilet implements deleteToilet operation.
//
// Deletes the Toilet with the requested ID.
//
// DELETE /toilets/{id}
func (UnimplementedHandler) DeleteToilet(ctx context.Context, params DeleteToiletParams) (r DeleteToiletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Deletes the User with the requested ID.
//
// DELETE /users/{id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCat implements listCat operation.
//
// List Cats.
//
// GET /cats
func (UnimplementedHandler) ListCat(ctx context.Context, params ListCatParams) (r ListCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCatToilets implements listCatToilets operation.
//
// List attached Toilets.
//
// GET /cats/{id}/toilets
func (UnimplementedHandler) ListCatToilets(ctx context.Context, params ListCatToiletsParams) (r ListCatToiletsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListToilet implements listToilet operation.
//
// List Toilets.
//
// GET /toilets
func (UnimplementedHandler) ListToilet(ctx context.Context, params ListToiletParams) (r ListToiletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUser implements listUser operation.
//
// List Users.
//
// GET /users
func (UnimplementedHandler) ListUser(ctx context.Context, params ListUserParams) (r ListUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUserCats implements listUserCats operation.
//
// List attached Cats.
//
// GET /users/{id}/cats
func (UnimplementedHandler) ListUserCats(ctx context.Context, params ListUserCatsParams) (r ListUserCatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadCat implements readCat operation.
//
// Finds the Cat with the requested ID and returns it.
//
// GET /cats/{id}
func (UnimplementedHandler) ReadCat(ctx context.Context, params ReadCatParams) (r ReadCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadCatOwner implements readCatOwner operation.
//
// Find the attached User of the Cat with the given ID.
//
// GET /cats/{id}/owner
func (UnimplementedHandler) ReadCatOwner(ctx context.Context, params ReadCatOwnerParams) (r ReadCatOwnerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadToilet implements readToilet operation.
//
// Finds the Toilet with the requested ID and returns it.
//
// GET /toilets/{id}
func (UnimplementedHandler) ReadToilet(ctx context.Context, params ReadToiletParams) (r ReadToiletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadToiletCat implements readToiletCat operation.
//
// Find the attached Cat of the Toilet with the given ID.
//
// GET /toilets/{id}/cat
func (UnimplementedHandler) ReadToiletCat(ctx context.Context, params ReadToiletCatParams) (r ReadToiletCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadUser implements readUser operation.
//
// Finds the User with the requested ID and returns it.
//
// GET /users/{id}
func (UnimplementedHandler) ReadUser(ctx context.Context, params ReadUserParams) (r ReadUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCat implements updateCat operation.
//
// Updates a Cat and persists changes to storage.
//
// PATCH /cats/{id}
func (UnimplementedHandler) UpdateCat(ctx context.Context, req *UpdateCatReq, params UpdateCatParams) (r UpdateCatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateToilet implements updateToilet operation.
//
// Updates a Toilet and persists changes to storage.
//
// PATCH /toilets/{id}
func (UnimplementedHandler) UpdateToilet(ctx context.Context, req *UpdateToiletReq, params UpdateToiletParams) (r UpdateToiletRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// Updates a User and persists changes to storage.
//
// PATCH /users/{id}
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
