// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Shuri-Honda-1101/cat-utils/ent/cat"
	"github.com/Shuri-Honda-1101/cat-utils/ent/toilet"
	"github.com/google/uuid"
)

// ToiletCreate is the builder for creating a Toilet entity.
type ToiletCreate struct {
	config
	mutation *ToiletMutation
	hooks    []Hook
}

// SetTime sets the "time" field.
func (tc *ToiletCreate) SetTime(t time.Time) *ToiletCreate {
	tc.mutation.SetTime(t)
	return tc
}

// SetType sets the "type" field.
func (tc *ToiletCreate) SetType(t toilet.Type) *ToiletCreate {
	tc.mutation.SetType(t)
	return tc
}

// SetMemo sets the "memo" field.
func (tc *ToiletCreate) SetMemo(s string) *ToiletCreate {
	tc.mutation.SetMemo(s)
	return tc
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tc *ToiletCreate) SetNillableMemo(s *string) *ToiletCreate {
	if s != nil {
		tc.SetMemo(*s)
	}
	return tc
}

// SetCatID sets the "cat" edge to the Cat entity by ID.
func (tc *ToiletCreate) SetCatID(id uuid.UUID) *ToiletCreate {
	tc.mutation.SetCatID(id)
	return tc
}

// SetNillableCatID sets the "cat" edge to the Cat entity by ID if the given value is not nil.
func (tc *ToiletCreate) SetNillableCatID(id *uuid.UUID) *ToiletCreate {
	if id != nil {
		tc = tc.SetCatID(*id)
	}
	return tc
}

// SetCat sets the "cat" edge to the Cat entity.
func (tc *ToiletCreate) SetCat(c *Cat) *ToiletCreate {
	return tc.SetCatID(c.ID)
}

// Mutation returns the ToiletMutation object of the builder.
func (tc *ToiletCreate) Mutation() *ToiletMutation {
	return tc.mutation
}

// Save creates the Toilet in the database.
func (tc *ToiletCreate) Save(ctx context.Context) (*Toilet, error) {
	return withHooks[*Toilet, ToiletMutation](ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ToiletCreate) SaveX(ctx context.Context) *Toilet {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *ToiletCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *ToiletCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *ToiletCreate) check() error {
	if _, ok := tc.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Toilet.time"`)}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Toilet.type"`)}
	}
	if v, ok := tc.mutation.GetType(); ok {
		if err := toilet.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Toilet.type": %w`, err)}
		}
	}
	return nil
}

func (tc *ToiletCreate) sqlSave(ctx context.Context) (*Toilet, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *ToiletCreate) createSpec() (*Toilet, *sqlgraph.CreateSpec) {
	var (
		_node = &Toilet{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(toilet.Table, sqlgraph.NewFieldSpec(toilet.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Time(); ok {
		_spec.SetField(toilet.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(toilet.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.Memo(); ok {
		_spec.SetField(toilet.FieldMemo, field.TypeString, value)
		_node.Memo = value
	}
	if nodes := tc.mutation.CatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toilet.CatTable,
			Columns: []string{toilet.CatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cat_toilets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ToiletCreateBulk is the builder for creating many Toilet entities in bulk.
type ToiletCreateBulk struct {
	config
	builders []*ToiletCreate
}

// Save creates the Toilet entities in the database.
func (tcb *ToiletCreateBulk) Save(ctx context.Context) ([]*Toilet, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Toilet, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToiletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *ToiletCreateBulk) SaveX(ctx context.Context) []*Toilet {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *ToiletCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *ToiletCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
